### PR TITLE
v4

### PR DESCRIPTION
**Pull request by puemos**
- New tech
- New design
- ts -> mp4 using ffmpeg

### CODE REVIEW

**Comment by shape55** [comment]
I just saw this update after posting [comments](https://github.com/puemos/hls-downloader/issues/213#issuecomment-2083875182) for the enhancement request.  Why does the Mozilla Store still have the [old version](https://addons.mozilla.org/en-US/firefox/addon/hls-downloader/)? Are there instructions how to install this for Firefox from the zip file?

**Comment by shape55** [comment]
Hi, any word on this, as I'd like to install the latest version?

**Comment by puemos** [comment]
Yesterday v4 became available on firefox

**Comment by shape55** [comment]
Oh nice, thank you.  I just tried it, and this version removed the options to paste in a URL, which was the only way I was able to download certain m3u8 files at all.  If I paste in a m3u8 link in the URL, Firefox just downloads it as an m3u8 "playlist" by default, and doesn't give me the option to download the actual video.  And m3u8 download sites give me an error with certain ones.  I'm not sure what else to try now.

For videos that do appear in the extension’s Sniffer window, I’m still not seeing a way to select mp4 as a file format.  Also, after downloading, the Save button in the Downloads window doesn’t do anything.

And the 2nd video I tested got stuck at 77%, and there’s no way to clear or cancel it.

**Comment by puemos** [comment]
Got it. Let's move this discussion to an issue.

**Pull request merged**
